namespace Resources.Models;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; } = null!;
    public decimal Price { get; set; }

    public Product(string name, decimal price)
    {
        Id = new Random().Next(1000, 9999);
        Name = name;
        Price = price;
    }
    //generated by ChatGPT 4o 
    public bool IsValid()
    {
        return !string.IsNullOrWhiteSpace(Name) && Price > 0;
    }

    public override string ToString()
    {
        return $"ID: {Id}, Namn: {Name}, Pris: {Price} kr";
    }
}
